-- AlterEnum
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_MESSAGING_MESSAGE_HIDE';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_MESSAGING_MESSAGE_REDACT';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_MESSAGING_THREAD_REOPEN';
ALTER TYPE "AdminAuditAction" ADD VALUE IF NOT EXISTS 'ADMIN_MESSAGING_SYSTEM_MESSAGE';
