import { PrismaService } from 'src/prisma/prisma.service';
import { CustomOrderPricingService } from 'src/custom-order-pricing/custom-order-pricing.service';
import { LedgerService } from 'src/finance/ledger.service';
import { CustomOrderRefundService } from './custom-order-refund.service';
import { CustomOrderSideEffectsService } from './custom-order-side-effects.service';
import { AcceptCustomOrderDto, BrandRespondToCustomOrderExtensionCounterDto, CancelCustomOrderDto, ConfirmCustomOrderDeliveryDto, CreateExceptionReviewRequestDto, CreateCustomOrderDto, CreateCustomOrderExtensionRequestDto, CustomOrderChartFamily, CustomOrderPricePreviewDto, CustomOrderResolverPolicy, QueryCustomOrdersDto, RejectCustomOrderDto, ReportCustomOrderIssueDto, RespondToCustomOrderExtensionDto, UpdateDisplayChartPreferenceDto, UpdateCustomOrderMeasurementsDto, UpdateCustomOrderLifecycleStatusDto, UpdateCustomOrderProgressStageDto } from './dto/custom-orders.dto';
export declare class CustomOrdersService {
    private readonly prisma;
    private readonly pricingService;
    private readonly sideEffects;
    private readonly refundService;
    private readonly ledgerService;
    constructor(prisma: PrismaService, pricingService: CustomOrderPricingService, sideEffects: CustomOrderSideEffectsService, refundService: CustomOrderRefundService, ledgerService: LedgerService);
    createPricePreview(userId: string, dto: CustomOrderPricePreviewDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            checkoutIntentId: any;
            configurationId: string;
            configurationVersionId: string;
            currency: string;
            buyerPriceSummary: any;
            priceLockExpiresAt: any;
            quoteStatus: "MANUAL_QUOTE_REQUIRED";
            pricingChartFamily: CustomOrderChartFamily;
            displayChartFamily: CustomOrderChartFamily;
            resolverPolicy: CustomOrderResolverPolicy;
            computedSize: any;
            chartVersionId: string;
            noDirectMatch: boolean;
            conversionGuidance: string;
        };
    } | {
        statusCode: number;
        message: string;
        data: {
            checkoutIntentId: string;
            configurationId: string;
            configurationVersionId: string;
            currency: string;
            buyerPriceSummary: import("src/custom-order-pricing/custom-order-pricing.service").CustomOrderPriceSummary;
            priceLockExpiresAt: string;
            quoteStatus: "AUTO_PRICED";
            pricingChartFamily: CustomOrderChartFamily;
            displayChartFamily: CustomOrderChartFamily;
            resolverPolicy: CustomOrderResolverPolicy;
            computedSize: any;
            chartVersionId: string;
            noDirectMatch: boolean;
            conversionGuidance: string;
        };
    }>;
    createOrder(userId: string, dto: CreateCustomOrderDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    listBuyerOrders(userId: string, query: QueryCustomOrdersDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            items: {
                id: string;
                status: import("@prisma/client").$Enums.CustomOrderStatus;
                paymentStatus: import("@prisma/client").$Enums.PaymentStatus;
                sourceType: import("@prisma/client").$Enums.CustomOrderSourceType;
                sourceId: string;
                sourceTitle: string;
                brand: {
                    name: string;
                };
                buyerPriceSummary: {
                    grandTotal: unknown;
                    currency: string;
                };
                currentProgressStage: import("@prisma/client").$Enums.CustomOrderProgressStage;
                createdAt: Date;
            }[];
            page: number;
            limit: number;
            total: number;
        };
    }>;
    getBuyerOrder(userId: string, customOrderId: string): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    cancelBuyerOrder(userId: string, customOrderId: string, dto: CancelCustomOrderDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    confirmDelivery(userId: string, customOrderId: string, dto: ConfirmCustomOrderDeliveryDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    reportIssue(userId: string, customOrderId: string, dto: ReportCustomOrderIssueDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    respondToExtension(userId: string, customOrderId: string, requestId: string, dto: RespondToCustomOrderExtensionDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    respondToBuyerCounter(ownerUserId: string, brandId: string, customOrderId: string, requestId: string, dto: BrandRespondToCustomOrderExtensionCounterDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    getDisplayChartPreference(userId: string): Promise<{
        statusCode: number;
        message: string;
        data: {
            displayChartFamily: CustomOrderChartFamily;
            updatedAtMs: number;
        };
    }>;
    updateDisplayChartPreference(userId: string, dto: UpdateDisplayChartPreferenceDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            displayChartFamily: CustomOrderChartFamily;
            updatedAtMs: number;
        };
    }>;
    createExceptionReviewRequest(ownerUserId: string, brandId: string, customOrderId: string, dto: CreateExceptionReviewRequestDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    listBrandOrders(ownerUserId: string, brandId: string, query: QueryCustomOrdersDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            items: {
                id: string;
                status: import("@prisma/client").$Enums.CustomOrderStatus;
                paymentStatus: import("@prisma/client").$Enums.PaymentStatus;
                sourceType: import("@prisma/client").$Enums.CustomOrderSourceType;
                sourceId: string;
                sourceTitle: string;
                brand: {
                    name: string;
                };
                buyerPriceSummary: {
                    grandTotal: unknown;
                    currency: string;
                };
                currentProgressStage: import("@prisma/client").$Enums.CustomOrderProgressStage;
                createdAt: Date;
            }[];
            page: number;
            limit: number;
            total: number;
        };
    }>;
    getBrandOrder(ownerUserId: string, brandId: string, customOrderId: string): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    acceptBrandOrder(ownerUserId: string, brandId: string, customOrderId: string, dto: AcceptCustomOrderDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    rejectBrandOrder(ownerUserId: string, brandId: string, customOrderId: string, dto: RejectCustomOrderDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    updateBrandProgressStage(ownerUserId: string, brandId: string, customOrderId: string, dto: UpdateCustomOrderProgressStageDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    createExtensionRequest(ownerUserId: string, brandId: string, customOrderId: string, dto: CreateCustomOrderExtensionRequestDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    updateLifecycleStatus(ownerUserId: string, brandId: string, customOrderId: string, dto: UpdateCustomOrderLifecycleStatusDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    updateBuyerMeasurementsBeforeAcceptance(userId: string, customOrderId: string, dto: UpdateCustomOrderMeasurementsDto): Promise<{
        statusCode: number;
        message: string;
        data: {
            id: any;
            status: any;
            paymentStatus: any;
            paymentReference: any;
            source: {
                type: any;
                id: any;
                title: any;
                slug: any;
                primaryMediaUrl: any;
                brandName: any;
            };
            configurationVersionId: any;
            buyerPriceSummary: any;
            internalPriceBreakdown: any;
            quoteStatus: string;
            chartLock: Record<string, unknown>;
            exceptionDecision: Record<string, unknown> | null;
            measurementSnapshot: any;
            measurementConfirmedAt: any;
            currentProgressStage: any;
            acceptedAt: any;
            buyerAcceptedAt: any;
            completedAt: any;
            promisedProductionAt: any;
            promisedDispatchAt: any;
            promisedDeliveryAt: any;
            buyerAcceptanceWindowEndsAt: any;
            measurementRetentionUntil: any;
            anonymizedAt: any;
            retentionHoldType: any;
            retentionHoldReason: any;
            retentionHoldUntil: any;
            retentionHoldSetById: any;
            retentionHoldSetAt: any;
            progressEvents: any;
            extensionRequests: any;
            issues: any;
            disputes: any;
            timelineEvents: any;
            createdAt: any;
            updatedAt: any;
        };
    }>;
    private queueBuyerNotification;
    private queueBrandNotification;
    private listOrders;
    private requireBuyerOrder;
    private resolveBrand;
    private assertBrandOwnership;
    private getActiveConfiguration;
    private getConfigurationVersion;
    private conditionsFromSnapshot;
    private buildCheckoutIntentRequestSnapshot;
    private normalizeCheckoutIntentRequestSnapshot;
    private normalizeChartLock;
    private normalizeChartFamily;
    private normalizeResolverPolicy;
    private currentChartVersionId;
    private validateAndNormalizeIssueEvidence;
    private buildDisputeIntakeQuestions;
    private resolveAdditionalYardsFromProfile;
    private parseConfigurationYardProfile;
    private resolveChartEvaluation;
    private inferMeasurementGenderFromKeys;
    private resolveBaselineMeasurementKeys;
    private resolveRequiredMeasurementKeys;
    private validateMeasurementRanges;
    private resolveSourceSnapshot;
    private resolveStageThreshold;
    private isExtensionRequestAllowed;
    private isLifecycleTransitionAllowed;
    private applyExtensionDays;
    private mapListItem;
    private mapDetail;
    private get detailIncludes();
}
