export const REVIEW_ERRORS = {
    NOT_ELIGIBLE: 'REVIEW_NOT_ELIGIBLE',
    ALREADY_EXISTS: 'REVIEW_ALREADY_EXISTS',
    BLOCKED_BY_DISPUTE: 'REVIEW_BLOCKED_BY_DISPUTE',
    MEDIA_OWNERSHIP_INVALID: 'REVIEW_MEDIA_OWNERSHIP_INVALID',
    MEDIA_TYPE_INVALID: 'REVIEW_MEDIA_TYPE_INVALID',
    NOT_FOUND: 'REVIEW_NOT_FOUND',
    FORBIDDEN: 'REVIEW_FORBIDDEN',
    ALREADY_VOTED: 'REVIEW_ALREADY_VOTED_HELPFUL',
    REPORT_EXISTS: 'REVIEW_REPORT_ALREADY_EXISTS',
    FEATURE_DISABLED: 'REVIEW_FEATURE_DISABLED',
} as const;

export const REVIEW_FEATURE_FLAGS = {
    READ: 'reviews.v1.read',
    WRITE: 'reviews.v1.write',
    BRAND_REPLIES: 'reviews.v1.brand-replies',
    ADMIN_MODERATION: 'reviews.v1.admin-moderation',
    REMINDERS: 'reviews.v1.reminders',
} as const;
